name: build_ErfanGSIs

on:
#  release:
#    types: [published]
  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://aablzpjaephbx664cho5os3arznw6888.node.ppio.cloud:48106/fsa167af8c.a.bdydns.com/1435501072/Firmware/Flyme/meizu17/9.2.0.3/cn/20220424185818/498fa997/update.zip?f_ver=v1&max_age=7776000&r=MAIZRDl3aVoeBxRUT1MTJnYbCF0wOGgWFwNJf1FADDQ5BAgbDCE%2FGB1BC1xRSBRyb1lUGnhjdltLQQVXFwBRcWpGWQZ%2BfH5AQF9eFgwLWSU5T1QDZTg2ERkaAxdCWxE3BghaKSkoRBceA1dbVg9y&ppiouid=62b378c222ab8400011120dc741a5de8&ppio_auth=62b378c2__0_e6d3b5c95b469244f98a0f035198f163
  ROM_NAME: Flyme
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
#       - name: Clean Up
#         run: |
#           docker rmi `docker images -q`
#           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
#           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
#           sudo -E apt-get update
#           sudo -E apt-get -y autoremove --purge
#           sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
        
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh

       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME -b
       
       - name: 7z GSI  
         run: |
              mkdir final
              sudo apt-get install p7zip
              7z a -t7z -r final/GSI.7z /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/*AB*
       
       - name: Upload GSI to wet
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet final/GSI.7z

         
            
